name: static

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: cleanup
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependecies
        run: |
          sudo apt-get update
          sudo apt-get install texlive-full 
      - name: Build figures
        run: |
          ./build.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: |
            *.pdf
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Delete old deployment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true
